// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BenchmarkReport {
    /**
     * Creates a new BenchmarkReport instance.
     * @param {Partial<BenchmarkReport>} [$$source = {}] - The source object to create the BenchmarkReport.
     */
    constructor($$source = {}) {
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {ProbeResult[]}
             */
            this["results"] = [];
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {BenchmarkSummary}
             */
            this["summary"] = (new BenchmarkSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BenchmarkReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BenchmarkReport}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField1_0($$parsedSource["summary"]);
        }
        return new BenchmarkReport(/** @type {Partial<BenchmarkReport>} */($$parsedSource));
    }
}

export class BenchmarkSummary {
    /**
     * Creates a new BenchmarkSummary instance.
     * @param {Partial<BenchmarkSummary>} [$$source = {}] - The source object to create the BenchmarkSummary.
     */
    constructor($$source = {}) {
        if (!("fastestMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fastestMs"] = 0;
        }
        if (!("slowestMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["slowestMs"] = 0;
        }
        if (!("hasResults" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasResults"] = false;
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BenchmarkSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BenchmarkSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BenchmarkSummary(/** @type {Partial<BenchmarkSummary>} */($$parsedSource));
    }
}

export class ProbeResult {
    /**
     * Creates a new ProbeResult instance.
     * @param {Partial<ProbeResult>} [$$source = {}] - The source object to create the ProbeResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("iconUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconUrl"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("latencyMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latencyMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProbeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeResult(/** @type {Partial<ProbeResult>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("intervalMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["intervalMinutes"] = 0;
        }
        if (!("targets" in $$source)) {
            /**
             * @member
             * @type {Target[]}
             */
            this["targets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

export class Target {
    /**
     * Creates a new Target instance.
     * @param {Partial<Target>} [$$source = {}] - The source object to create the Target.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("iconUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Target instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Target}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Target(/** @type {Partial<Target>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ProbeResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = BenchmarkSummary.createFrom;
const $$createType3 = Target.createFrom;
const $$createType4 = $Create.Array($$createType3);
