// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} source
 * @returns {$CancellablePromise<$models.BenchmarkReport>}
 */
export function Benchmark(source) {
    return $Call.ByID(3945575655, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<$models.DNSTestReport>}
 */
export function BenchmarkDNS(source) {
    return $Call.ByID(3530690002, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(4061041145).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(864400823);
}

/**
 * @returns {$CancellablePromise<$models.MyIPReport>}
 */
export function RefreshMyIP() {
    return $Call.ByID(1209743392).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {$models.Settings} settings
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(1922714600, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowSettings() {
    return $Call.ByID(3790064556);
}

// Private type creation functions
const $$createType0 = $models.BenchmarkReport.createFrom;
const $$createType1 = $models.DNSTestReport.createFrom;
const $$createType2 = $models.Settings.createFrom;
const $$createType3 = $models.MyIPReport.createFrom;
